version: "3.8"

services:
  core:
    build:
      context: ./core
      dockerfile: Dockerfile
    container_name: core_api
    ports:
      - "8081:8080" #int:ext
    env_file:
      - ./core/.env
    restart: unless-stopped
  
  aibot:
    build:
      context: ./aibot
      dockerfile: Dockerfile
    container_name: aibot_service
    ports:
      - "8082:8080" #int:ext
    env_file:
      - ./aibot/.env
    restart: unless-stopped

  ggbot:
    build:
      context: ./ggbot
      dockerfile: Dockerfile
    container_name: ggbot_service
    env_file:
      - ./aibot/.env
    restart: unless-stopped
    depends_on:
      - core